name: rfi_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.0

  # Authentication & Database
  pocketbase: ^0.23.0+1
  url_launcher: ^6.3.0

  # Storage
  shared_preferences: ^2.3.2

  # Navigation
  go_router: ^16.2.1

  # UI & Design
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1

  # Utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
